FROM odoo:17.0

USER root

# Installez les outils nécessaires
RUN apt-get update && apt-get install -y \
    postgresql-client \
    iputils-ping \
    net-tools \
    locales \
    && apt-get clean

# Configurer les locales
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

USER odoo

CMD ["odoo"]
